# .gitlab-ci.yml
 
variables:
  NOTEBOOK: "quick-start-to-quantum/solutions/01_quick_start_to_quantum.ipynb"
 
test-one-notebook:
  image: ghcr.io/nvidia/cudaqx
  script:
    - apt-get update -qq && apt-get install -y -qq libgfortran5
    - pip install --quiet --upgrade jupyter nbconvert
    - echo "Running $NOTEBOOK"
    - jupyter nbconvert
        --to notebook
        --execute
        --inplace
        --ExecutePreprocessor.timeout=600
        --ExecutePreprocessor.kernel_name=python3
        "$NOTEBOOK"
  artifacts:
    when: always
    paths:
      - "$NOTEBOOK"
    expire_in: 1 week
 